authentik:
  secret_key: "PleaseGenerateA50CharKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.beryju.org, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"

postgresql:
  enabled: true
  postgresqlPassword: "ThisIsNotASecurePassword"

volumes:
  - name: assets
    configMap:
      name: authentik-assets

volumeMounts:
  - name: assets
    mountPath: /media/assets
