authentik_bootstrap_password  = "1234"
authentik_endpoint_domain     = "localhost:9000"
authentik_endpoint_protocol   = "http"
authentik_nextit_clientid     = "nextit-clientid"
authentik_nextit_clientsecret = "nextit-clientsecret"
web_postgres_password         = "postgres"
