authentik_bootstrap_password  = "1234"
authentik_bootstrap_token     = "5678"
authentik_endpoint            = "http://localhost:9000"
authentik_nextit_clientid     = "nextit-clientid"
authentik_nextit_clientsecret = "nextit-clientsecret"
